# Chapter 3 - Exercise 5: IRIS FLOWERS
### Cho dữ liệu IRIS flowers từ ['https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data']('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')
1. Import dữ liệu từ URL trên, tạo array iris và giữ nguyên dữ liệu text => In shape, In 3 dòng đầu của dữ liệu
2. Import dữ liệu từ URL trên, tạo array iris_2d trong đó chỉ lấy 4 cột đầu, kiểu float
3. Với dữ liệu của câu trên, tạo array sepallength với giá trị lấy từ cột đầu tiên của iris_2d. Tính mean, median, standard deviation, min, max of iris's sepallength
4. Tìm điểm số % của sepallength thứ 5th và 95th 
5. Lọc các dòng theo điều kiện: Lọc các dòng của iris_2d có petallength (3rd column) > 1.5 và sepallength (1st column) < 5.0
6. Tìm correlation giữa SepalLength(1st column) và PetalLength(3rd column) của iris_2d
7. Tìm vị trí của các dòng missing value trong array
* Sử dụng URL của IRIS, tạo array iris_2d_temp
* Chỉnh lại một số dòng ngẫu nhiên có giá trị null ở các cột ngẫu nhiên: thêm vào trị nul (nan) tại 20 vị trí ngẫu nhiên trong array
* Đếm các giá trị nan
* Hiển thị vị trí các dòng này
* Hiển thị các dòng này
* Xóa các dòng dữ liệu nan trong array
* Kiểm tra lại xem array có còn giá trị nan hay không?

In [1]:
import numpy as np
# Câu 1: Import dữ liệu, tạo array và giữ nguyên dữ liệu text
# Từ 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# Với các cột: 'sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
print(iris.shape)
# in 3 dòng đầu
print(iris[:3])

(150, 5)
[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']]


In [2]:
# Câu 2: Import dữ liệu từ URL, tạo array trong đó chỉ lấy 4 cột đầu, kiểu float
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
print(iris_2d.shape)
print(iris_2d[:3])

(150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]


In [3]:
# Câu 3: Với dữ liệu của câu trên, tạo 1 array mới với giá trị lấy từ cột đầu tiên 
# Tính mean, median, standard deviation, min, max of iris's sepallength
sepallength = iris_2d[:,0]
print(sepallength[:3])
mu, med, sd, smin, smax = np.mean(sepallength), np.median(sepallength), np.std(sepallength), np.min(sepallength), np.max(sepallength)
print(mu, med, sd, smin, smax)

[5.1 4.9 4.7]
5.843333333333334 5.8 0.8253012917851409 4.3 7.9


In [4]:
# Câu 3': Tạo array từ cột đầu của dữ liệu từ URL, chuẩn hóa dữ liệu cột này trong khoảng có giá trị từ 0 đến 1
sepallength_1 = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
print(sepallength_1[:5])

[5.1 4.9 4.7 4.6 5. ]


In [5]:
# Câu 4:  percentile scores of a numpy array
# Tìm điểm số % của sepallength thứ 5th và 95th 
print(np.percentile(sepallength, q=[5, 95]))

[4.6   7.255]


In [6]:
# Câu 5: Lọc các dòng theo điều kiện
# Lọc các dòng của iris_2d có petallength (3rd column) > 1.5 và sepallength (1st column) < 5.0
condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
print(iris_2d[condition])

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [7]:
# Câu 6: Tìm corellation
# Tìm correlation giữa SepalLength(1st column) và PetalLength(3rd column) của iris_2d
c = np.corrcoef(iris_2d[:, 0], iris_2d[:, 2])
print(c)
print(c[0,1])
'''
# Correlation coef indicates the degree of linear relationship between two numeric variables.
# It can range between -1 to +1.

# The p-value roughly indicates the probability of an uncorrelated system producing 
# datasets that have a correlation at least as extreme as the one computed.
# The lower the p-value (<0.01), stronger is the significance of the relationship.
# It is not an indicator of the strength.
#> 0.871754157305
'''

[[1.         0.87175416]
 [0.87175416 1.        ]]
0.871754157304871


'\n# Correlation coef indicates the degree of linear relationship between two numeric variables.\n# It can range between -1 to +1.\n\n# The p-value roughly indicates the probability of an uncorrelated system producing \n# datasets that have a correlation at least as extreme as the one computed.\n# The lower the p-value (<0.01), stronger is the significance of the relationship.\n# It is not an indicator of the strength.\n#> 0.871754157305\n'

In [8]:
# Câu 7: Tìm vị trí của các dòng missing value trong array
# Sử dụng URL của IRIS, tạo array
#chỉnh lại một số dòng ngẫu nhiên có giá trị nan ở các cột ngẫu nhiên: thêm vá trị nan tại 20 vị trí ngẫu nhiên trong array
# Đếm các giá trị nan
# Hiển thị vị trí các dòng này
# Hiển thị các dòng này
iris_2d_temp = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d_temp[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
nums_nan = np.isnan(iris_2d_temp[:, 0]).sum()
print("Number of missing values: ", nums_nan)
pos = np.where(np.isnan(iris_2d_temp[:, 0]))
print("Position of missing values:",pos)
print(iris_2d_temp[pos,:])

Number of missing values:  5
Position of missing values: (array([  2,  14,  46,  77, 145], dtype=int32),)
[[[nan 3.2 1.3 0.2]
  [nan 4.  1.2 0.2]
  [nan 3.8 1.6 0.2]
  [nan 3.  5.  1.7]
  [nan 3.  5.2 2.3]]]


In [10]:
# Câu 8: Kiểm tra xem các bộ dữ liệu có null hay không
# Xóa dòng dữ liệu nan
print("Number of missing values (before): ", nums_nan)
pos = np.where(np.isnan(iris_2d_temp[:, 0]))
iris_2d_temp = iris_2d_temp[~np.isnan(iris_2d_temp).any(axis=1)]
nums_nan = np.isnan(iris_2d_temp[:, 0]).sum()
print("Number of missing values (after): ", nums_nan)

Number of missing values (before):  5
Number of missing values (after):  0
