# Chapter 3 - exercise 1: Hãy thực hiện các yêu cầu sau:
1. Tạo numpy array có giá trị từ 0 - 9, in array, type, shape
2. Từ numpy array ở câu 1 => tạo arr_odd và arr_even => in 2 array mới này
3. Từ numpy array ở câu 1 => tạo arr_update_1 với các phần tử chẵn giữ nguyên, các phần tử lẻ thay bằng 100 => in kết quả
4. Từ 2 array => tạo arr mới chỉ chứa các phần tử xuất hiện ở cả 2 array, lấy duy nhất, dùng np.intersect1d(a,b)
5. Từ 2 array a và b ở câu trên => Tạo array mới chỉ chứa các phần tử chỉ xuất hiện ở array a, dùng np.setdiff1d(a,b)
6. Cho array e, tạo array f chỉ chứa các phần tử có giá trị từ 5 đến 10 của e
7. Tạo array có 10 phần tử 0, cập nhật phần tử ở vị trí thứ 5 là 1
8. Tạo array có giá trị từ 10 đến 24
9. Cho array k => tạo array l từ k với các phần tử đếu khác 0
10. Từ array của câu trên, thêm 2 phần tử có giá trị là 10, 20 vào cuối array
11. Từ array của câu trên, thêm phần tử có giá trị 100 vào index = 5
12. Từ array của câu trên, xóa phần tử index = 0, 1, 2

In [1]:
import numpy as np
# Câu 1: Tạo numpy array có giá trị từ 0 - 9, in array, type, shape
arr = np.arange(10)
print(arr)
print(type(arr))
print(arr.shape)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(10,)


In [2]:
# Câu 2: Từ numpy array ở câu 1 => tạo arr_odd và arr_even => in 2 array mới này
arr_odd = arr[arr % 2 != 0]
print("Odd array:")
print(arr_odd)
print("Event array:")
arr_even = arr[arr % 2 == 0]
print(arr_even)

Odd array:
[1 3 5 7 9]
Event array:
[0 2 4 6 8]


In [3]:
# Câu 3: Từ numpy array ở câu 1 => tạo arr_update_1 với các phần tử chẵn giữ nguyên, các phần tử lẻ thay bằng 100
# in kết quả
array_update_1 = arr
array_update_1[array_update_1 % 2 != 0 ] = 100
print(array_update_1)

[  0 100   2 100   4 100   6 100   8 100]


In [4]:
# Câu 4: Tạo arr mới chỉ chứa các phần tử xuất hiện ở cả 2 array, lấy duy nhất
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.intersect1d(a,b)
print(c)

[2 4]


In [5]:
# Câu 5: Từ 2 array a và b ở câu trên => Tạo array mới chỉ chứa các phần tử chỉ xuất hiện ở array a
d = np.setdiff1d(a,b)
print(d)

[1 3 5 6]


In [6]:
# Câu 6: Cho array e, tạo array f chỉ chứa các phần tử có giá trị từ 5 đến 10 của e
e = np.array([2, 6, 1, 9, 10, 3, 27, 8, 6, 25, 16])
f = e[(e >= 5) & (e <= 10)]
print(f)

[ 6  9 10  8  6]


In [7]:
# Câu 7: Tạo array có 10 phần tử 0, cập nhật phần tử ở vị trí thứ 5 là 1
g = np.zeros(10)
print(g)
g[4] = 1
print(g)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
# Câu 8: Tạo array có giá trị từ 12 đến 24
h = np.arange(12, 25)
print(h)
# Đảo ngược array này
h = h[::-1]
print(h)

[12 13 14 15 16 17 18 19 20 21 22 23 24]
[24 23 22 21 20 19 18 17 16 15 14 13 12]


In [9]:
# Câu 9: Cho array k => tạo array l từ k với các phần tử đếu khác 0
k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0])
print(k)
l = k[k.nonzero()]
print(l)

[1 2 0 8 2 0 1 3 0 5 0]
[1 2 8 2 1 3 5]


In [10]:
# Câu 10: Từ array của câu trên, thêm 2 phần từ có giá trị là 10, 20 vào cuối array
l = np.append(l, [10, 20])
print(l)


[ 1  2  8  2  1  3  5 10 20]


In [11]:
# Câu 11: Từ array của câu trên, thêm phần tử có giá trị 100 vào index = 5
l = np.insert(l, 5, 100)
print(l)

[  1   2   8   2   1 100   3   5  10  20]


In [12]:
# Câu 12: Từ array của câu trên, xóa phần tử index = 0, 1, 2
l = np.delete(l, [0, 1, 2])
print(l)

[  2   1 100   3   5  10  20]
