## Mảng nhiều chiều

In [20]:
import numpy as np
# Tạo mảng
array_2 = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2)
print(type(array_2))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [21]:
print(array_2)
print(array_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [22]:
# truy xuất phần tử trong mảng
print(array_2)
print(array_2[1,2])
print(array_2[1,])

[[1 2 3]
 [4 5 6]]
6
[4 5 6]


In [23]:
# cập nhật
array_2[0][0] = 100
print(array_2)

[[100   2   3]
 [  4   5   6]]


In [24]:
# thay đổi kích cỡ mảng
print(array_2)
print(array_2.shape)
array_2.shape = (3,2) 
print(array_2)

[[100   2   3]
 [  4   5   6]]
(2, 3)
[[100   2]
 [  3   4]
 [  5   6]]


In [34]:
# tạo mảng với 0 hoặc 1
mang_zeros = np.zeros([2,2,2], dtype = int) 
print("Mảng zeros")
print(mang_zeros)
print("Mảng ones")
mang_ones = np.ones([2,2], dtype = int) 
print(mang_ones)

Mảng zeros
[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]
Mảng ones
[[1 1]
 [1 1]]


In [30]:
# thay đổi kích cỡ mảng dùng reshape
a = np.arange(24) 
print(a)
b = a.reshape(2, 3, 4) # ma trận, dòng, cột
print(b)
print(b[0][1][2]) 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
6


In [37]:
print(b)
print("b[0][1][2] =", b[0][1][2]) # ma trận 0, dòng 1, cột 2

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
b[0][1][2] = 6


In [43]:
print(b)
b1 = b[1:]
print("b1:")
print(b1)
b1_x_2 = b[1,...,2]
print("b1_x_2:")
print(b1_x_2)
b11_x = b[1,1,...]
print("b11_x:")
print(b11_x)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
b1:
[[[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
b1_x_2:
[14 18 22]
b11_x:
[16 17 18 19]
