## Tính toán trên mảng nhiều chiều

In [2]:
import numpy as np
a = np.array([[1, 2, 3, 4],[1, 1, 1, 1],[1, 2, 3, 4],[2, 2, 2, 2]]) 
b = np.array([2, 4, 6, 8])  
print(a)
print(b)
print("a + b")
print(a + b)
print("a - b")
print(a - b)
print("a * b")
print(a * b)
print("a / b")
print(a / b)

[[1 2 3 4]
 [1 1 1 1]
 [1 2 3 4]
 [2 2 2 2]]
[2 4 6 8]
a + b
[[ 3  6  9 12]
 [ 3  5  7  9]
 [ 3  6  9 12]
 [ 4  6  8 10]]
a - b
[[-1 -2 -3 -4]
 [-1 -3 -5 -7]
 [-1 -2 -3 -4]
 [ 0 -2 -4 -6]]
a * b
[[ 2  8 18 32]
 [ 2  4  6  8]
 [ 2  8 18 32]
 [ 4  8 12 16]]
a / b
[[0.5        0.5        0.5        0.5       ]
 [0.5        0.25       0.16666667 0.125     ]
 [0.5        0.5        0.5        0.5       ]
 [1.         0.5        0.33333333 0.25      ]]


In [14]:
c = np.array([[1, 2, 3, 4]]) 
print(c)
print("a * c")
print(a * c)


[[1 2 3 4]]
a * c
[[ 1  4  9 16]
 [ 1  2  3  4]
 [ 1  4  9 16]
 [ 2  4  6  8]]


## Statistic

In [21]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]])
print(a)

[[3 7 5]
 [8 4 3]
 [2 4 9]]


In [27]:
print("Max:", np.amax(a))
print("Min:", np.amin(a))
print("Max - theo từng cột:", np.amax(a, 0))
print("Min - theo từng cột:", np.amin(a, 0))
print("Max - theo từng dòng:", np.amax(a, 1))
print("Min - theo từng dòng:", np.amin(a, 1))

Max: 9
Min: 2
Max - theo từng cột: [8 7 9]
Min - theo từng cột: [2 4 3]
Max - theo từng dòng: [7 8 9]
Min - theo từng dòng: [3 3 2]


## Median, mean

In [35]:
b = np.array([[[3,7],[8,4]],[[2,4], [1, 5]]])
print(b)
print('Mean b:')
print(np.mean(b))
print('Mean b[0]:')
print(np.mean(b[0]))

[[[3 7]
  [8 4]]

 [[2 4]
  [1 5]]]
Mean b:
4.25
Mean b[0]:
5.5


In [36]:
print(b)
print('Median b:')
print(np.median(b))
print('Median b[1]:')
print(np.median(b[1]))

[[[3 7]
  [8 4]]

 [[2 4]
  [1 5]]]
Median b:
4.0
Median b[1]:
3.0


## Sort, where, extract


In [39]:
c = np.array([[[9,7],[8,4]],[[2,4], [6, 5]]])
print(c)
print("Sort c")
print(np.sort(c))

[[[9 7]
  [8 4]]

 [[2 4]
  [6 5]]]
Sort c
[[[7 9]
  [4 8]]

 [[2 4]
  [5 6]]]


In [41]:
print('Sort c[0] axis 0 (theo cột):')
print(np.sort(c[0], axis = 0))

Sort c[0] axis 0:
[[8 4]
 [9 7]]


In [42]:
print('Sort c[0] axis 1 (theo dòng):')
print(np.sort(c[0], axis = 1))

Sort c[0] axis 1 (theo dòng):
[[7 9]
 [4 8]]


In [43]:
dt = np.dtype([('name', 'S10'),('age', int)]) 
ds = np.array([("Tom",21),("Jenny",25),("Herry", 17), ("Matt",27)], dtype = dt) 
print(ds)

[(b'Tom', 21) (b'Jenny', 25) (b'Herry', 17) (b'Matt', 27)]


In [44]:
print('Order by name:')
print(np.sort(ds, order = 'name'))
print('Order by age:')
print(np.sort(ds, order = 'age'))

Order by name:
[(b'Herry', 17) (b'Jenny', 25) (b'Matt', 27) (b'Tom', 21)]
Order by age:
[(b'Herry', 17) (b'Tom', 21) (b'Jenny', 25) (b'Matt', 27)]


In [51]:
print(c)
cond = np.where(c>5)
print(cond)
print(c[cond])

[[[9 7]
  [8 4]]

 [[2 4]
  [6 5]]]
(array([0, 0, 0, 1], dtype=int32), array([0, 0, 1, 1], dtype=int32), array([0, 1, 0, 0], dtype=int32))
[9 7 8 6]


In [56]:
print(c)
print("Trên c:",np.extract(c >= 5, c))
print("Trên c[0]:",np.extract(c[0] >= 5, c[0]))


[[[9 7]
  [8 4]]

 [[2 4]
  [6 5]]]
Trên c: [9 7 8 6 5]
Trên c[0]: [9 7 8]


In [4]:
# Tính toán độ lệch chuẩn standard deviation
a = np.array([[1, 2], [3, 4]])
print(a)
print(np.std(a))
print(np.std(a, axis = 0))
print(np.std(a, axis = 1))

[[1 2]
 [3 4]]
1.118033988749895
[1. 1.]
[0.5 0.5]


In [9]:
a = np.array([[1,4,6], [1,2,3]])
print(a)
print("Coefficient")
print(np.corrcoef(a[0],a[1]))

[[1 4 6]
 [1 2 3]]
Coefficient
[[1.         0.99339927]
 [0.99339927 1.        ]]
