In [3]:
import numpy as np 

a = np.array([1, 2, 3, 4]) 
b = np.array([5, 6, 7, 8]) 
mang_cong = a + b 
print(mang_cong)
mang_tru = a - b 
print(mang_tru)
mang_nhan = a * b 
print(mang_nhan)
mang_chia = a / b 
print(mang_chia)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [6]:
# max, min
d = np.array([3, 10, 9, 12, 8, 5])
print(np.amax(d))
print(np.amin(d))

12
3


In [8]:
print(d)
print(np.ptp(d, axis = 0))

[ 3 10  9 12  8  5]
9


In [9]:
print(d)
print(np.mean(d))

[ 3 10  9 12  8  5]
7.833333333333333


In [11]:
print(d)
print(np.median(d)) # 3, 5, 8, 9, 10, 12 => trung bình giữa = (8+9)/2

[ 3 10  9 12  8  5]
8.5


## Sort, search, counting

In [13]:
# numpy.sort(a, axis, kind, order)
mang_5 = np.array([3, 1, 2, 4, 7, 3, 8, 9, 5, 6])
print(mang_5)
print(np.sort(mang_5))

[3 1 2 4 7 3 8 9 5 6]
[1 2 3 3 4 5 6 7 8 9]


In [18]:
print(mang_5)
indexes = np.where(mang_5 >= 5)
print(indexes)
print(mang_5[indexes])

[3 1 2 4 7 3 8 9 5 6]
(array([4, 6, 7, 8, 9], dtype=int32),)
[7 8 9 5 6]


In [20]:
print(mang_5)
print(np.extract(np.mod(mang_5,2)==0, mang_5))
print(np.extract(mang_5 >= 5, mang_5))

[3 1 2 4 7 3 8 9 5 6]
[2 4 8 6]
[7 8 9 5 6]
