numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

### Ví dụ tạo mảng

In [3]:
import numpy as np 
# Mảng một chiều
np.array([1,2,3]) 
print(a)

[1 2 3]


In [4]:
# Mảng hai chiều
a = np.array([[1, 2, 3], [4, 5, 6]]) 
print(a)

[[1 2 3]
 [4 5 6]]


In [5]:
# ndmin & dtype
a = np.array([1, 2, 3, 4, 5], ndmin = 2, dtype = complex) 
print(a)

[[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]]


numpy.dtype(object, align, copy)

In [6]:
dt = np.dtype(np.int32) 
print(dt)

int32


In [1]:
# file name can be used to access content of age column 
import numpy as np 

dt = np.dtype([('age','i8')]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print(a['age'])

[10 20 30]


### Note: int8, int16, int32, int64 có thể thay thế bằng  can be replaced by equivalent string 'i1', 'i2','i4'