In [2]:
import numpy as np
x = [1,2,3] 
a = np.asarray(x) 
print(a)

[1 2 3]


In [2]:
# Mảng với các phần tử có giá trị ban đầu là 0
mang = np.zeros((5,), dtype = np.int) 
print(mang)

[0 0 0 0 0]


In [3]:
# Mảng với các phần tử có giá trị ban đầu là 1
mang_1 = np.ones(5) 
print(mang_1)

[1. 1. 1. 1. 1.]


In [4]:
# Tạo mảng từ Tuple
x = (1, 2, 3) 
a = np.asarray(x) 
print(a)

[1 2 3]


## Tạo mảng với range, sử dụng: numpy.arange(start, stop, step, dtype)

In [5]:
mang_2 = np.arange(10,20,2) 
print(mang_2)

[10 12 14 16 18]


## Tạo mảng với range có khoảng cách đều nhau, sử dụng: numpy.linspace(start, stop, num, endpoint, retstep, dtype)

In [7]:
mang_3 = np.linspace(10,20, 5) 
print(mang_3)
mang_4 = np.linspace(10,20, 5, endpoint = False) 
print(mang_4)

[10.  12.5 15.  17.5 20. ]
[10. 12. 14. 16. 18.]


In [15]:
# Truy xuất phần tử trong mảng
mang_4 = np.array([1, 3, 2, 4, 5, 7, 9])
print(mang_4)
print(mang_4[3])
print(mang_4[3:])
print(mang_4[3:5])
print(mang_4[mang_4 < 5]) # có kèm điều kiện

[1 3 2 4 5 7 9]
4
[4 5 7 9]
[4 5]
[1 3 2 4]


In [11]:
# Truy xuất các phần tử trong mảng dùng slice
mang_5 = np.arange(10)
print(mang_5)
s = slice(3,8,2) 
print(mang_5[s])
print(mang_5[s][1])


[0 1 2 3 4 5 6 7 8 9]
[3 5 7]
5


In [3]:
# Thêm các phần tử vào cuối mảng
mang_5 = np.arange(10)
mang_5  = np.append(mang_5, [25, 30])
print(mang_5)

[ 0  1  2  3  4  5  6  7  8  9 25 30]


In [4]:
# Thêm phần từ vào index = 3, giá trị 100
print(mang_5)
mang_5 = np.insert(mang_5, 3, 100)
print(mang_5)

[ 0  1  2  3  4  5  6  7  8  9 25 30]
[  0   1   2 100   3   4   5   6   7   8   9  25  30]


In [6]:
# Xóa phần tử tại vị trí index = 11
print(mang_5)
mang_5 = np.delete(mang_5, 11)
print(mang_5)

[  0   1   2 100   3   4   5   6   7   8   9  25  30]
[  0   1   2 100   3   4   5   6   7   8   9  30]
